# Generated by Django 6.0.6 on 2026-07-15 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accom_want', models.CharField(blank=True, max_length=10)),
                ('accom_pref', models.CharField(blank=True, max_length=200)),
                ('song_request', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_child', models.BooleanField(default=False)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diet', models.CharField(blank=True, max_length=500)),
                ('other_diet', models.CharField(blank=True, max_length=300)),
                ('alcohol', models.CharField(blank=True, max_length=500)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='core.rsvpsubmission')),
            ],
        ),
    ]
